# -*- coding: utf-8 -*-
"""learning_field.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8-Ezu51ojydHQ4YNcyYzxMacKkdxfFl
"""

import ast
import pandas as pd

data = pd.read_csv("programmers.csv", encoding = "UTF-8")

# 삭제할 행의 인덱스를 저장할 리스트를 생성합니다.
drop_index_list = []

# 'section-summary' 컬럼의 각 행을 순회합니다.
for i in range(len(data)):
    # 각 행의 데이터를 ast.literal_eval을 이용해서 리스트로 변환합니다.
    row_data = ast.literal_eval(data['section-summary'].iloc[i])

    # '직무'라는 단어가 포함되어 있는지 확인합니다.
    has_job = any('직무' in sub_list[0] for sub_list in row_data)

    # '직무'라는 단어가 없다면 해당 행의 인덱스를 저장합니다.
    if not has_job:
        drop_index_list.append(data.index[i])
    else:
        for sub_list in row_data:
            if '직무' in sub_list[0]:
                sub_list[1] = sub_list[1].replace('\n', '')
                sub_list[1] = sub_list[1].replace(' ', '')
                # '직무' 뒤에 나오는 내용으로 'section-summary'를 변경합니다.
                data.at[i, 'section-summary'] = sub_list[1]
                break

# 저장한 인덱스에 해당하는 행을 한 번에 삭제합니다.
data.drop(drop_index_list, inplace=True)

# 인덱스를 재설정합니다.
data.reset_index(drop=True, inplace=True)

print(data['section-summary'])

data = data[data['section-stack'].map(len) > 2]
data = data.reset_index(drop=True)
print(data['section-stack'])

# 'section-summary'와 'section-stack' 열만 선택하여 새로운 DataFrame을 만듭니다.
new_data = data[['section-summary', 'section-stack']]

# 새로운 DataFrame을 csv 파일로 저장합니다.
new_data.to_csv('new_programmers.csv', index=False)